# Generated by Django 5.2.9 on 2025-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_menuitem_category_remove_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
